services:
  mongodb:
    image: mongo:8.0.0-rc4
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data_container:
