name: tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  clojure:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    env:
      NATS_NEW_ORDERS: ${{ vars.NATS_NEW_ORDERS }}
      NATS_URL: ${{ secrets.NATS_URL }}
      NATS_APP_NAME: ${{ vars.NATS_APP_NAME }}
      NATS_PUBLISH_NEW_PAYMENT: ${{ vars.NATS_PUSLISH_NEW_PAYMENT }}
      NATS_PUBLISH_STATUS: ${{ vars.NATS_PUBLISH_STATUS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # It is important to install java before installing clojure tools which needs java
      # exclusions: babashka, clj-kondo and cljstyle
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "22"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.3.1463 # Clojure CLI based on tools.deps

      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
          wait: true

      - name: Execute build
        run: clojure -T:build ci

      # - name: Execute BDD (cucumber)
      #   run: clojure -M:test:cucumber -g ./test/mba_fiap/ ./test/resources/

      # - name: Execute tests
      #   run: clojure -X:test

      # (Optionally) When you don't need Testcontainers anymore, you could terminate sessions eagerly
      - name: Terminate Testcontainers Cloud Client active sessions
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          action: terminate

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [clojure]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
